import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const extra = localfont({
  src: [
    {
      path: "../public/font/DejaVuSans-ExtraLight.ttf",
    },
  ],
  variable: "--font-extra",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={extra.variable}>{children}</body>
    </html>
  );
}
